import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Writes a finished dictation into the application in front without going
/// through an input-method client: the text is put on the pasteboard and ⌘V is
/// posted. It works with any input source selected and in applications that
/// never attach an IMK client (terminals, some Electron fields). Posting key
/// events needs the Accessibility permission.
enum AccessibilityInserter {
    static var isTrusted: Bool { AXIsProcessTrusted() }

    static func requestTrust() {
        let options = ["AXTrustedCheckOptionPrompt": true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }

    /// Clipboard managers skip items carrying these markers (nspasteboard.org).
    private static let transientTypes = [NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
                                         NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")]
    /// Slow clients read the pasteboard some time after ⌘V arrives.
    private static let restoreDelay: Duration = .milliseconds(1200)
    private typealias SavedItems = [[(NSPasteboard.PasteboardType, Data)]]
    /// The user's own contents while a dictation sits on the pasteboard. A second
    /// paste inside the window must restore these, not the first dictation.
    @MainActor private static var pendingRestore: (items: SavedItems, ownedCount: Int)?

    /// Paste `text` at the caret of the frontmost application, then put the
    /// user's own pasteboard contents back. Returns false when the keystroke
    /// could not be posted; the pasteboard is untouched in that case.
    @MainActor
    static func paste(_ text: String) -> Bool {
        guard !text.isEmpty, isTrusted,
              let source = CGEventSource(stateID: .combinedSessionState) else { return false }
        let key = pasteKeyCode()
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false) else { return false }
        let pasteboard = NSPasteboard.general
        let previous: SavedItems
        if let pending = pendingRestore, pasteboard.changeCount == pending.ownedCount {
            previous = pending.items
        } else {
            // Preserve all representations of every item, not only plain text.
            previous = pasteboard.pasteboardItems?.map { item in
                item.types.compactMap { type -> (NSPasteboard.PasteboardType, Data)? in
                    item.data(forType: type).map { (type, $0) }
                }
            } ?? []
        }
        func restore() {
            pasteboard.clearContents()
            let items = previous.map { values in
                let item = NSPasteboardItem()
                for (type, data) in values { item.setData(data, forType: type) }
                return item
            }
            pasteboard.writeObjects(items)
        }
        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else { restore(); return false }
        for type in transientTypes { pasteboard.setData(Data(), forType: type) }
        let ownedCount = pasteboard.changeCount
        pendingRestore = (previous, ownedCount)
        for event in [down, up] {
            // Exactly ⌘V, whatever modifier the user may still be holding.
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: InputEvent.syntheticUserData)
            event.post(tap: .cghidEventTap)
        }
        Task { @MainActor in
            try? await Task.sleep(for: restoreDelay)
            // A later paste took over the restore.
            guard pendingRestore?.ownedCount == ownedCount else { return }
            pendingRestore = nil
            // Only restore if nobody else has written to the pasteboard meanwhile.
            guard pasteboard.changeCount == ownedCount else { return }
            restore()
        }
        return true
    }

    /// Last resort: leave the text on the pasteboard for a manual ⌘V.
    @MainActor
    static func copy(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    /// The key that produces "v" together with Command in the layout in use, so
    /// Dvorak and "Dvorak – QWERTY ⌘" users get a paste and not another shortcut.
    static func pasteKeyCode() -> CGKeyCode {
        let fallback = CGKeyCode(kVK_ANSI_V)
        guard let layout = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let raw = TISGetInputSourceProperty(layout, kTISPropertyUnicodeKeyLayoutData) else { return fallback }
        let data = Unmanaged<CFData>.fromOpaque(raw).takeUnretainedValue() as Data
        let command = UInt32((cmdKey >> 8) & 0xFF)
        return data.withUnsafeBytes { bytes -> CGKeyCode in
            guard let keyboard = bytes.bindMemory(to: UCKeyboardLayout.self).baseAddress else { return fallback }
            var candidates = [UInt16(kVK_ANSI_V)]
            candidates.append(contentsOf: (0..<UInt16(50)).filter { $0 != UInt16(kVK_ANSI_V) })
            for code in candidates {
                var deadKeys: UInt32 = 0
                var length = 0
                var characters = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(keyboard, code, UInt16(kUCKeyActionDown), command, UInt32(LMGetKbdType()),
                                            OptionBits(1 << kUCKeyTranslateNoDeadKeysBit), &deadKeys,
                                            characters.count, &length, &characters)
                if status == noErr, length == 1, characters[0] == UniChar(UInt8(ascii: "v")) {
                    return CGKeyCode(code)
                }
            }
            return fallback
        }
    }
}
