import Foundation

@main struct OverlayNoticeTests {
    @MainActor static func wait(_ milliseconds: Int) async { try? await Task.sleep(for: .milliseconds(milliseconds)) }
    @MainActor static func main() async {
        let overlay = OverlayController(displaysPanel: false)
        overlay.showLanguageSwitch(from: "English", to: "简体中文", duration: 0.025)
        precondition(overlay.model.languageSwitch?.from == "English" && overlay.model.languageSwitch?.to == "简体中文")
        await wait(60)
        precondition(overlay.model.languageSwitch == nil)
        overlay.showLanguageSwitch(from: "English", to: "中文", duration: 0.025)
        await wait(10)
        overlay.showLanguageSwitch(from: "中文", to: "日本語", duration: 0.10)
        await wait(45)
        precondition(overlay.model.languageSwitch?.to == "日本語", "Old timeout must not hide new switch")
        await wait(90)
        precondition(overlay.model.languageSwitch == nil)
        overlay.showLanguageSwitch(from: "中文", to: "English", duration: 0.025)
        overlay.show(source: "中文", target: "EN", liveInject: true, hotkeyLabel: "右⌘")
        overlay.setPhase(.listening)
        await wait(60)
        precondition(overlay.model.languageSwitch == nil && overlay.model.phase == .listening)
        overlay.showLanguageSwitch(from: "中文", to: "日本語", duration: 0.025)
        precondition(overlay.model.languageSwitch == nil, "Notice must not cover recording")
        overlay.hide()
        overlay.showLanguageSwitch(from: "中文", to: "English", duration: 0.025)
        overlay.hide(); await wait(50)
        precondition(overlay.model.languageSwitch == nil && overlay.model.phase == .hidden)
        overlay.showCompletion(.polishFailed, duration: 0.025)
        precondition(overlay.model.completion == .polishFailed)
        await wait(60)
        precondition(overlay.model.completion == nil)
        overlay.showCompletion(.polishTimedOut, duration: 0.025)
        overlay.show(source: "中文", target: "EN", liveInject: true, hotkeyLabel: "右⌘")
        overlay.setPhase(.polishing)
        await wait(60)
        precondition(overlay.model.phase == .polishing && overlay.model.completion == nil)
        overlay.showCompletion(.unchanged)
        precondition(overlay.model.completion == nil, "Completion cannot cover an active session")
        overlay.hide()
        for feedback in [CompletionFeedback.ordinary, .polished, .unchanged] {
            overlay.showCompletion(feedback)
            precondition(overlay.model.completion == nil && overlay.model.phase == .hidden)
        }
        overlay.showConversionFailure(duration: 0.025)
        precondition(overlay.model.phase == .error)
        await wait(60)
        precondition(overlay.model.phase == .hidden)
        overlay.showCompletion(.polishFailed, duration: 0.025)
        overlay.showConversionFailure()
        precondition(overlay.model.completion == .polishFailed && overlay.model.phase == .hidden)
        overlay.hide()
        overlay.showConversionFailure(duration: 0.025)
        overlay.show(source: "中文", target: "EN", liveInject: true, hotkeyLabel: "右⌘")
        overlay.setPhase(.listening)
        await wait(60)
        precondition(overlay.model.phase == .listening)
        overlay.hide()
        print("PASS: language notice labels, expiry, repeat switch, recording priority and explicit hide")
    }
}
